server:
  port: 8081

spring:
  application:
    name: hr-worker
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

